name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DEVELOPER_DIR: /Applications/Xcode_11.5.app/Contents/Developer

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Package update
      run: swift package update
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
